user: ProNeverFake
template: classic
base: header, activity, community, repositories, metadata

plugin_languages: yes
plugin_languages_ignored: html, css
plugin_languages_details: bytes-size, percentage
plugin_followup: yes
plugin_stars: yes
plugin_reactions: yes
plugin_lines: yes
